name: gluon_vision_docs
dependencies:
- python
- sphinx>=1.5.5
- scipy
- numpy
- matplotlib
- sphinx_rtd_theme
- pip:
  - https://github.com/mli/mx-theme/tarball/master
  - sphinx-gallery
  - mxnet-cu92==1.4.0b20181202
  # - guzzle_sphinx_theme
  - recommonmark
  - Image
  - awscli
  - tqdm
  - requests
  - Pillow
  - opencv-python
